const fs = require('fs');
const filePath = 'index.html';

// HTMLファイルを読み込む
let content = fs.readFileSync(filePath, 'utf-8');

// アプリ名の英語 → 日本語マップ（100個）
const replacements = {
  "Weather": "天気",
  "Calendar": "カレンダー",
  "Camera": "カメラ",
  "Contacts": "連絡先",
  "Gallery": "ギャラリー",
  "Clock": "時計",
  "Calculator": "電卓",
  "Settings": "設定",
  "Music": "音楽",
  "Videos": "ビデオ",
  "Notes": "メモ",
  "Maps": "地図",
  "Phone": "電話",
  "Messages": "メッセージ",
  "Browser": "ブラウザ",
  "Files": "ファイル",
  "Email": "メール",
  "Reminders": "リマインダー",
  "News": "ニュース",
  "App Store": "アプリストア",
  "Health": "ヘルスケア",
  "Wallet": "ウォレット",
  "Books": "ブック",
  "Podcasts": "ポッドキャスト",
  "Translator": "翻訳",
  "Shortcuts": "ショートカット",
  "Compass": "コンパス",
  "Measure": "計測",
  "Tips": "ヒント",
  "Voice Memos": "ボイスメモ",
  "Stocks": "株価",
  "Home": "ホーム",
  "TV": "テレビ",
  "Game Center": "ゲームセンター",
  "iTunes Store": "iTunesストア",
  "FaceTime": "FaceTime",
  "Find My": "探す",
  "Files": "ファイル",
  "Watch": "ウォッチ",
  "Activity": "アクティビティ",
  "Fitness": "フィットネス",
  "Weather Pro": "天気プロ",
  "My Calendar": "私のカレンダー",
  "Secure Camera": "セキュアカメラ",
  "Contact Manager": "連絡先管理",
  "Photo Vault": "フォトボールト",
  "World Clock": "ワールドクロック",
  "Smart Calculator": "スマート電卓",
  "Quick Settings": "クイック設定",
  "Music Player": "ミュージックプレイヤー",
  "Video Stream": "ビデオストリーム",
  "Sticky Notes": "付箋メモ",
  "Offline Maps": "オフライン地図",
  "Dialer": "ダイヤラー",
  "SMS Manager": "SMSマネージャー",
  "Web Explorer": "ウェブエクスプローラー",
  "File Manager": "ファイルマネージャー",
  "Email Client": "メールクライアント",
  "Reminder Pro": "リマインダープロ",
  "News Feed": "ニュースフィード",
  "App Market": "アプリ市場",
  "Health Tracker": "健康管理",
  "Digital Wallet": "デジタルウォレット",
  "eBook Reader": "電子書籍リーダー",
  "Audio Cast": "オーディオキャスト",
  "Live Translate": "ライブ翻訳",
  "Macro Shortcuts": "マクロショートカット",
  "Smart Compass": "スマートコンパス",
  "AR Measure": "AR計測",
  "User Tips": "ユーザーヒント",
  "Voice Notes": "音声メモ",
  "Stock Market": "株式市場",
  "Home Control": "ホームコントロール",
  "TV Remote": "テレビリモコン",
  "Game Hub": "ゲームハブ",
  "Media Store": "メディアストア",
  "Video Call": "ビデオ通話",
  "Device Locator": "デバイスロケーター",
  "Document Viewer": "ドキュメントビューア",
  "Smart Watch": "スマートウォッチ",
  "Daily Activity": "日々の活動",
  "Workout Log": "ワークアウトログ",
  "Weather Japan": "日本の天気",
  "Holiday Calendar": "休日カレンダー",
  "Baby Camera": "ベビーカメラ",
  "Business Contacts": "ビジネス連絡先",
  "Hidden Gallery": "非表示ギャラリー",
  "Alarm Clock": "アラーム時計",
  "Math Solver": "数学ソルバー",
  "System Settings": "システム設定",
  "Music Streamer": "音楽ストリーマー",
  "Video Hub": "ビデオハブ",
  "Quick Memo": "クイックメモ",
  "GPS Maps": "GPS地図",
  "Call Log": "通話履歴",
  "Messenger Pro": "メッセンジャープロ",
  "Web Browser": "ウェブブラウザ",
  "Documents": "ドキュメント",
  "Mail Reader": "メールリーダー",
  "Task Scheduler": "タスクスケジューラ",
  "Top News": "トップニュース"
};

// アプリ名を一括で置換
for (const [english, japanese] of Object.entries(replacements)) {
  const regex = new RegExp(english, 'g');
  content = content.replace(regex, japanese);
}

// ファイルに書き戻す
fs.writeFileSync(filePath, content, 'utf-8');

console.log("✅ 100個の英語アプリ名を日本語に変換しました。");
